fix(ci): add missing deps for building Python deps
Without `python3-dev` and `build-essential` build of `pyzstd` fails with:
```
error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
```

Signed-off-by: Jakub Sokołowski <jakub@status.im>