fix(status-go): skip Nix shell use to avoid Glibc errors
Linux builds on desktop are stuck with:
```
/usr/bin/ld: .../libstatus.so: undefined reference to `pthread_mutexattr_init@GLIBC_2.34'
/usr/bin/ld: .../libstatus.so: undefined reference to `dlclose@GLIBC_2.34'
/usr/bin/ld: .../libstatus.so: undefined reference to `pthread_detach@GLIBC_2.34'
```
Due to using old Glibc 2.34 from Ubuntu 22.04 while Nix uses 2.38.

Signed-off-by: Jakub Sokołowski <jakub@status.im>